// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-OgkxhgaRMrvEp9GMhVu4pQPu4oWYdw',
    appId: '1:407807209811:web:cbf7acd7fe1fc0c325b1a6',
    messagingSenderId: '407807209811',
    projectId: 'ecommerceapp-7851c',
    authDomain: 'ecommerceapp-7851c.firebaseapp.com',
    storageBucket: 'ecommerceapp-7851c.firebasestorage.app',
    measurementId: 'G-TN9Q0YZ868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDMXljVhvCBSIM2iIYo56r8U4-ag1X6U',
    appId: '1:407807209811:android:1838c96cbd3a968625b1a6',
    messagingSenderId: '407807209811',
    projectId: 'ecommerceapp-7851c',
    storageBucket: 'ecommerceapp-7851c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcqykdlNnF7cunxizFxKP9R3uu6cOtEf8',
    appId: '1:407807209811:ios:c2fcc3394ce9915625b1a6',
    messagingSenderId: '407807209811',
    projectId: 'ecommerceapp-7851c',
    storageBucket: 'ecommerceapp-7851c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppPhp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcqykdlNnF7cunxizFxKP9R3uu6cOtEf8',
    appId: '1:407807209811:ios:c2fcc3394ce9915625b1a6',
    messagingSenderId: '407807209811',
    projectId: 'ecommerceapp-7851c',
    storageBucket: 'ecommerceapp-7851c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppPhp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-OgkxhgaRMrvEp9GMhVu4pQPu4oWYdw',
    appId: '1:407807209811:web:b2cb8ec6a193285125b1a6',
    messagingSenderId: '407807209811',
    projectId: 'ecommerceapp-7851c',
    authDomain: 'ecommerceapp-7851c.firebaseapp.com',
    storageBucket: 'ecommerceapp-7851c.firebasestorage.app',
    measurementId: 'G-G2VBJZHK8T',
  );
}